package com.ad.sakain_chatbot.utilities;

public interface SDKBotParams {
    String ASSISTANT_API_KEY = "ASSISTANT_API_KEY_AR";
    String ASSISTANT_ID_AR = "ASSISTANT_ID_AR";
    String ASSISTANT_URL = "ASSISTANT_URL_AR";
    String ASSISTANT_VERSION_AR = "ASSISTANT_VERSION_AR";


    String ASSISTANT_ID_EN = "ASSISTANT_ID_EN";
    String ASSISTANT_VERSION_EN = "ASSISTANT_VERSION_EN";

    String TEXT_TO_SPEECH_API_KEY = "TEXT_TO_SPEECH_API_KEY";
    String TEXT_TO_SPEECH_SERVICES_URL = "TEXT_TO_SPEECH_SERVICES_URL";

    String SPEECH_TO_TEXT_API_KEY = "SPEECH_TO_TEXT_API_KEY";
    String SPEECH_TO_TEXT_SERVICES_URL = "SPEECH_TO_TEXT_SERVICES_URL";
}
